language: python
services:
  - mysql
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - mysql -u root -e 'CREATE DATABASE treeD;'
  - mysql -u root -e "CREATE USER 'makler'@'localhost' IDENTIFIED BY 'makler';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'usuario'@'localhost';"
script:
  - cd treeD
  - python manage.py test 
